export { default as Sidebar } from './Sidebar/index.vue'
export { default as TagsView } from './TagsView'
export { default as AppMain } from './AppMain'
export { default as TopBar } from './TopBar'
// export { default as SidebarNew } from './SidebarNew/index.vue'
